FROM deploy-frontend:latest AS build

WORKDIR /app
COPY . /app
RUN npm run build

FROM deploy-frontend:latest

RUN apk add --no-cache nginx

COPY nginx.conf /etc/nginx/http.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
