FROM deploy-backend:latest

WORKDIR /app
ENV PYTHONPATH=/app
ENV WEB_CONCURRENCY=4

COPY app /app/app
COPY sql /app/sql
COPY alembic /app/alembic
COPY alembic.ini /app/alembic.ini

CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers ${WEB_CONCURRENCY:-4}"]
